//> using scala 3.5.2
//> using dep org.typelevel::laika-core:1.3.2
//> using dep com.lihaoyi::os-lib:0.11.8

// Static site generator for rosualinpetru.github.io.
//
//   scala-cli run build.scala                                        -> local build (output/)
//   scala-cli run build.scala -- --site-url https://example.com      -> production build (adds feed URL metadata)
//
// Content layout:
//   content/pages/*.md  -> standalone pages ("home" slug becomes index.html)
//   content/blog/*.md   -> blog posts, listed at /blog/ and in the atom feed
//   content/extra/*     -> copied verbatim to the site root (cv.pdf)
//   static/             -> copied verbatim (stylesheet, images)
//
// Colors: the whole palette is derived at build time from the dominant
// saturated hue of static/img/portrait.jpg (see paletteCss). Swap the photo
// and the site recolors itself; set AccentOverride to pin a hue manually.

import laika.api.Transformer
import laika.format.{HTML, Markdown}
import laika.config.SyntaxHighlighting

import java.awt.Color
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.util.Locale
import javax.imageio.ImageIO

val SiteName    = "Alin-Petru Roșu"
val Description =
  "Alin-Petru Roșu — cybersecurity engineer and researcher specialising in applied cryptography and PKI."

// Set to Some("#146b3a") (any hex) to pin the accent hue instead of deriving it from the portrait.
val AccentOverride: Option[String] = None

val NavLinks = List(
  "About"    -> "/",
  "Research" -> "/research/",
  "Projects" -> "/projects/",
  "Blog"     -> "/blog/",
  "CV"       -> "/cv.pdf"
)

val SocialLinks = List(
  "GitHub"   -> "https://github.com/rosualinpetru",
  "LinkedIn" -> "https://linkedin.com/in/rosualinpetru",
  "ORCID"    -> "https://orcid.org/0009-0005-8537-7265",
  "Email"    -> "mailto:rosualinpetru@gmail.com"
)

val root    = os.pwd
val content = root / "content"
val output  = root / "output"

val markdown = Transformer
  .from(Markdown)
  .to(HTML)
  .using(Markdown.GitHubFlavor, SyntaxHighlighting)
  .withRawContent // allow raw HTML blocks inside markdown (hero, research/projects entries)
  .build

val displayDate = DateTimeFormatter.ofPattern("MMM yyyy", Locale.ENGLISH)

final case class Doc(meta: Map[String, String], html: String):
  def title: String = meta.getOrElse("title", sys.error(s"missing Title in $meta"))
  def slug: String  = meta.getOrElse("slug", sys.error(s"missing Slug for '$title'"))

final case class Post(doc: Doc, date: LocalDate):
  export doc.{title, slug}
  def url: String = s"/blog/$slug/"

def parse(path: os.Path): Doc =
  val lines          = os.read(path).linesIterator.toList
  val (header, rest) = lines.span(_.nonEmpty)
  val MetaLine       = """^([A-Za-z_]+):\s*(.*)$""".r
  val meta           = header.collect { case MetaLine(k, v) => k.toLowerCase -> v.trim }.toMap
  val body           = rest.mkString("\n")
  val html           = markdown.transform(body).fold(err => sys.error(s"$path: $err"), identity)
  Doc(meta, html)

def escape(s: String): String =
  s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;")

// ---------------------------------------------------------------------------
// Palette
// ---------------------------------------------------------------------------

/** Dominant saturated hue of the portrait: a saturation-and-darkness weighted
  * hue histogram, so dark clothing wins over bright skin and background.
  */
def dominantHue(img: java.awt.image.BufferedImage): Float =
  val hsb    = new Array[Float](3)
  val weight = Array.fill(36)(0.0)
  val hueSum = Array.fill(36)(0.0)
  val step   = math.max(1, math.min(img.getWidth, img.getHeight) / 256)
  for x <- 0 until img.getWidth by step; y <- 0 until img.getHeight by step do
    val c = new Color(img.getRGB(x, y))
    Color.RGBtoHSB(c.getRed, c.getGreen, c.getBlue, hsb)
    val (h, s, b) = (hsb(0), hsb(1), hsb(2))
    if s > 0.15f && b > 0.06f && b < 0.95f then
      val w   = s * (1.2 - b)
      val bin = math.min(35, (h * 36).toInt)
      weight(bin) += w
      hueSum(bin) += h * w
  val top = weight.indices.maxBy(weight)
  (hueSum(top) / weight(top)).toFloat

def hex(h: Float, s: Float, b: Float): String =
  f"#${Color.HSBtoRGB(h, s, b) & 0xffffff}%06x"

def accentHue: Float =
  AccentOverride match
    case Some(hexStr) =>
      val c   = Color.decode(hexStr)
      val hsb = Color.RGBtoHSB(c.getRed, c.getGreen, c.getBlue, null)
      hsb(0)
    case None =>
      dominantHue(ImageIO.read((root / "static" / "img" / "portrait.jpg").toIO))

/** Every color on the site, derived from one hue. Neutral tones carry a hint
  * of the accent so the whole page feels related to the portrait.
  */
def paletteCss(h: Float): String =
  s"""/* Generated by build.scala from static/img/portrait.jpg — do not edit by hand. */
:root {
  --bg: ${hex(h, 0.02f, 0.99f)};
  --fg: ${hex(h, 0.10f, 0.14f)};
  --muted: ${hex(h, 0.09f, 0.42f)};
  --accent: ${hex(h, 0.62f, 0.36f)};
  --accent-soft: ${hex(h, 0.32f, 0.58f)};
  --surface: ${hex(h, 0.05f, 0.97f)};
  --rule: ${hex(h, 0.08f, 0.89f)};
  --code-bg: ${hex(h, 0.04f, 0.955f)};
  color-scheme: light dark;
}

@media (prefers-color-scheme: dark) {
  :root {
    --bg: ${hex(h, 0.14f, 0.08f)};
    --fg: ${hex(h, 0.03f, 0.91f)};
    --muted: ${hex(h, 0.06f, 0.63f)};
    --accent: ${hex(h, 0.34f, 0.80f)};
    --accent-soft: ${hex(h, 0.24f, 0.60f)};
    --surface: ${hex(h, 0.13f, 0.12f)};
    --rule: ${hex(h, 0.13f, 0.20f)};
    --code-bg: ${hex(h, 0.12f, 0.11f)};
  }
}
"""

def faviconSvg(accent: String): String =
  s"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <rect width="100" height="100" rx="22" fill="$accent"/>
  <text x="50" y="64" font-family="Georgia, serif" font-size="42" fill="#ffffff" text-anchor="middle">rap</text>
</svg>
"""

// ---------------------------------------------------------------------------
// Layout
// ---------------------------------------------------------------------------

def layout(title: String, main: String, active: String, feedUrl: Option[String]): String =
  val nav = NavLinks
    .map((n, l) =>
      val cls = if l == active then """ class="active"""" else ""
      s"""<a href="$l"$cls>$n</a>"""
    )
    .mkString("\n      ")
  val social = SocialLinks
    .map((n, l) =>
      val external = if l.startsWith("mailto") then "" else """ rel="me noopener" target="_blank""""
      s"""<a href="$l"$external>$n</a>"""
    )
    .mkString("\n      ")
  val feed = feedUrl.fold("")(u =>
    s"""\n  <link rel="alternate" type="application/atom+xml" title="$SiteName — blog feed" href="$u">"""
  )
  s"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escape(title)}</title>
  <meta name="description" content="$Description">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="/css/palette.css">
  <link rel="stylesheet" href="/css/style.css">$feed
</head>
<body>
  <header class="site-header">
    <a class="site-name" href="/">$SiteName</a>
    <nav>
      $nav
    </nav>
  </header>

  <main>
$main
  </main>

  <footer class="site-footer">
    <div class="social">
      $social
    </div>
    <div class="colophon">&copy; $SiteName</div>
  </footer>
</body>
</html>
"""

def pageHtml(doc: Doc): String =
  val heading = if doc.slug == "home" then "" else s"<h1>${escape(doc.title)}</h1>\n  "
  s"""<article class="page">
  $heading${doc.html}
</article>"""

def postHtml(post: Post): String =
  s"""<article class="post">
  <header>
    <h1>${escape(post.title)}</h1>
    <p class="meta"><time datetime="${post.date}">${post.date.format(displayDate)}</time></p>
  </header>
  ${post.doc.html}
  <p class="back"><a href="/blog/">&larr; All posts</a></p>
</article>"""

def blogIndexHtml(posts: List[Post]): String =
  val items =
    if posts.isEmpty then "<li>No posts yet.</li>"
    else
      posts
        .map(p => s"""<li>
    <time datetime="${p.date}">${p.date.format(displayDate)}</time>
    <a href="${p.url}">${escape(p.title)}</a>
  </li>""")
        .mkString("\n  ")
  s"""<h1>Blog</h1>
<p class="lede">Occasional technical notes on cryptography, security engineering, and things I am building.</p>
<ul class="post-list">
  $items
</ul>"""

def atomFeed(posts: List[Post], siteUrl: String): String =
  def ts(d: LocalDate) = s"${d}T00:00:00Z"
  val updated          = posts.headOption.map(p => ts(p.date)).getOrElse(ts(LocalDate.of(2026, 1, 1)))
  val entries = posts
    .map(p => s"""  <entry>
    <title>${escape(p.title)}</title>
    <link href="$siteUrl${p.url}"/>
    <id>$siteUrl${p.url}</id>
    <updated>${ts(p.date)}</updated>
    <content type="html">${escape(p.doc.html)}</content>
  </entry>""")
    .mkString("\n")
  s"""<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>$SiteName</title>
  <link href="$siteUrl/"/>
  <link rel="self" href="$siteUrl/feeds/all.atom.xml"/>
  <id>$siteUrl/</id>
  <updated>$updated</updated>
$entries
</feed>
"""

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

@main def build(args: String*): Unit =
  val siteUrl = args.toList match
    case "--site-url" :: url :: _ => Some(url.stripSuffix("/"))
    case _                        => None
  val feedUrl = siteUrl.map(_ + "/feeds/all.atom.xml")

  os.remove.all(output)
  os.makeDir.all(output)

  // Pages: content/pages/*.md — "home" lands at /, everything else at /<slug>/.
  val pages = os.list(content / "pages").filter(_.ext == "md").map(parse)
  pages.foreach { page =>
    val (dest, active) =
      if page.slug == "home" then (output / "index.html", "/")
      else (output / page.slug / "index.html", s"/${page.slug}/")
    os.write.over(dest, layout(s"${page.title} — $SiteName", pageHtml(page), active, feedUrl), createFolders = true)
  }

  // Posts: content/blog/*.md, newest first.
  val posts = os
    .list(content / "blog")
    .filter(_.ext == "md")
    .map(parse)
    .map(d => Post(d, LocalDate.parse(d.meta.getOrElse("date", sys.error(s"missing Date in '${d.title}'")))))
    .sortBy(_.date)(Ordering[LocalDate].reverse)
    .toList
  posts.foreach { post =>
    val dest = output / "blog" / post.slug / "index.html"
    os.write.over(dest, layout(s"${post.title} — $SiteName", postHtml(post), "/blog/", feedUrl), createFolders = true)
  }
  os.write.over(
    output / "blog" / "index.html",
    layout(s"Blog — $SiteName", blogIndexHtml(posts), "/blog/", feedUrl),
    createFolders = true
  )

  // Feed (production builds only — needs an absolute site URL).
  siteUrl.foreach(url => os.write.over(output / "feeds" / "all.atom.xml", atomFeed(posts, url), createFolders = true))

  // Verbatim files (before the generated palette: copy.over replaces whole directories).
  os.list(content / "extra").foreach(f => os.copy.over(f, output / f.last))
  os.list(root / "static").foreach(d => os.copy.over(d, output / d.last, createFolders = true))

  // Palette + favicon, derived from the portrait.
  val hue = accentHue
  os.write.over(output / "css" / "palette.css", paletteCss(hue), createFolders = true)
  os.write.over(output / "favicon.svg", faviconSvg(hex(hue, 0.62f, 0.36f)))

  println(s"Accent hue ${(hue * 360).round}° -> ${hex(hue, 0.62f, 0.36f)}")
  println(s"Built ${pages.size} pages and ${posts.size} posts into $output")
